"""
Convertit un export PDF de la recherche NOTAM de la FAA (« createNotamPdf.pdf ») en NOTAM de test pour le
simulateur local : un JSON par aéroport dans worker/notam_mock/ (OACI.json), au format compact du worker
(worker/notam.js) : { id, raw, text, from, to, q, scope, schedule }.

Le PDF mélange deux formats :
  - format OACI : « A1181/25 NOTAMN », puis Q) A) B) C) [D)] E) [F) G)] ;
  - format domestique américain : « !JFK 11/346 JFK TWY KG ... CLSD 2511192100-PERM » (pas de code Q ;
    « !FDC » pour les procédures) ; le site les classe alors d'après leur texte.
Les NOTAM d'annulation (NOTAMC) sont ignorés. L'heure de la requête (« Query ran at UTC ») est conservée :
le simulateur décale les dates pour que les NOTAM restent en vigueur comme au moment de l'export.

Usage : python scripts/parse_notam_pdf.py chemin/vers/createNotamPdf.pdf [--output worker/notam_mock]
Nécessite pdftotext (poppler).
"""

import argparse
import calendar
import html
import json
import os
import re
import subprocess
import sys

ICAO_START = re.compile(r"^([A-Z]\d{4}/\d{2}) NOTAM([NRC])\b")
DOMESTIC_START = re.compile(r"^!([A-Z0-9]{3,4}) (\d{1,2}/\d{1,4}) ")
FOOTER = re.compile(r"^\s*PDF generated by Federal NOTAM Systems.*$")
PAGE_TAG = re.compile(r"\s{2,}Page \d+ of \d+\s*$")
DOMESTIC_RANGE = re.compile(r"\s*(\d{10})-(\d{10}|PERM)(EST)?\s*$")


def notam_time(v):
    """« 2511192100 » (AAMMJJhhmm, UTC) -> secondes Unix."""
    m = re.fullmatch(r"(\d{2})(\d{2})(\d{2})(\d{2})(\d{2})", v or "")
    if not m:
        return None
    y, mo, d, h, mi = (int(x) for x in m.groups())
    try:
        return calendar.timegm((2000 + y, mo, d, h, mi, 0))
    except (ValueError, OverflowError):
        return None


def read_lines(pdf):
    text = subprocess.run(["pdftotext", "-layout", pdf, "-"], capture_output=True, check=True).stdout.decode("utf-8", "replace")
    lines = []
    for line in text.splitlines():
        if FOOTER.match(line):
            continue
        lines.append(html.unescape(PAGE_TAG.sub("", line)).rstrip())
    return lines


def query_time(lines):
    for line in lines[:15]:
        m = re.search(r"Query ran at UTC: (\d{2}) (\w{3}) (\d{4}) (\d{2})(\d{2}) UTC", line)
        if m:
            mon = ["Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"].index(m.group(2)) + 1
            return calendar.timegm((int(m.group(3)), mon, int(m.group(1)), int(m.group(4)), int(m.group(5)), 0))
    return None


def split_records(lines):
    records, cur = [], None
    for line in lines:
        if ICAO_START.match(line) or DOMESTIC_START.match(line):
            if cur:
                records.append(cur)
            cur = [line]
        elif cur is not None:
            cur.append(line)
    if cur:
        records.append(cur)
    return [("\n".join(r)).strip() for r in records]


def parse_icao(rec):
    head = ICAO_START.match(rec)
    if head.group(2) == "C":
        return None, []
    e = re.search(r"(?:^|\s)E\)\s*", rec)
    if not e:
        return None, []
    header, body = rec[:e.start()], rec[e.end():]
    body = re.split(r"(?:^|\s)[FG]\)", body)[0]
    q = re.search(r"Q\)\s*([A-Z0-9]{4})\s*/\s*(Q[A-Z]{4})", header)
    a = re.search(r"A\)\s*((?:[A-Z0-9]{4}\s*)+?)(?=\s*B\)|$)", header, re.S)
    b = re.search(r"B\)\s*(\d{10})", header)
    c = re.search(r"C\)\s*(\d{10}|PERM)\s*(EST)?", header)
    d = re.search(r"D\)\s*(.+?)\s*$", header, re.S)
    locs = re.findall(r"[A-Z0-9]{4}", a.group(1)) if a else []
    scope = None
    qline = re.search(r"Q\)\s*(\S.*)$", header, re.M)
    if qline:
        parts = [p.strip() for p in qline.group(1).split("/")]
        if len(parts) > 4:
            scope = {"A": "AERODROME", "E": "EN-ROUTE", "W": "NAV WARNING", "AE": "AERODROME", "AW": "AERODROME"}.get(parts[4])
    text = re.sub(r"[ \t]+\n", "\n", body).strip()
    return {
        "id": head.group(1),
        "raw": rec,
        "text": text,
        "from": notam_time(b.group(1)) if b else None,
        "to": notam_time(c.group(1)) if c and c.group(1) != "PERM" else None,
        "q": q.group(2) if q else None,
        "scope": scope,
        "schedule": re.sub(r"\s+", " ", d.group(1)) if d else None,
    }, locs


def parse_domestic(rec):
    m = DOMESTIC_START.match(rec)
    acct, num = m.group(1), m.group(2)
    rest = rec[m.end():]
    loc_m = re.match(r"([A-Z0-9]{3,4})\s+", rest)
    loc = loc_m.group(1) if loc_m else acct
    body = rest[loc_m.end():] if loc_m else rest
    rng = DOMESTIC_RANGE.search(body)
    start = end = None
    if rng:
        start = notam_time(rng.group(1))
        end = None if rng.group(2) == "PERM" else notam_time(rng.group(2))
        body = body[:rng.start()]
    icao = loc if len(loc) == 4 else "K" + loc
    return {
        "id": f"{acct} {num}",
        "raw": rec,
        "text": re.sub(r"\s*\n\s*", " ", body).strip(),
        "from": start,
        "to": end,
        "q": None,
        "scope": "AERODROME",
        "schedule": None,
    }, [icao]


def merge_parts(records):
    """Recolle les NOTAM domestiques en plusieurs parties (« !FDC 6/1519 MIA PART 1 OF 2 ... »)."""
    # Format OACI : « A) RJAA PART 2 OF 2 B) ... E) suite du texte » : seul le texte E) de la suite est gardé
    out = []
    for rec in records:
        m = re.match(r"^(!\S+ \S+ \S+) PART (\d+) OF \d+ ", rec)
        mi = ICAO_START.match(rec)
        part = re.search(r"\sPART (\d+) OF \d+\s", rec) if mi else None
        if m and int(m.group(2)) > 1 and out and out[-1].startswith(m.group(1) + " PART"):
            out[-1] += "\n" + rec[m.end():]
        elif part and int(part.group(1)) > 1 and out and out[-1].startswith(mi.group(0)):
            e = re.search(r"(?:^|\s)E\)\s*", rec)
            if e:
                out[-1] += "\n" + rec[e.end():]
        else:
            out.append(rec)
    out = [re.sub(r"\s*END PART \d+ OF \d+", "", re.sub(r"^(!\S+ \S+ \S+) PART 1 OF \d+ ", r"\1 ", r)) for r in out]
    return [re.sub(r"(A\)\s*(?:[A-Z0-9]{4}\s*)+)PART 1 OF \d+\s*", r"\1", r) if ICAO_START.match(r) else r for r in out]


def main():
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("pdf")
    ap.add_argument("--output", default=os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))), "worker", "notam_mock"))
    ap.add_argument("--verbose", action="store_true", help="affiche les NOTAM ignorés")
    args = ap.parse_args()

    lines = read_lines(args.pdf)
    queried = query_time(lines)
    by_airport, skipped = {}, 0
    for rec in merge_parts(split_records(lines)):
        n, locs = parse_icao(rec) if ICAO_START.match(rec) else parse_domestic(rec)
        if not n or not locs:
            skipped += 1
            if args.verbose:
                print("ignoré :", rec[:120].replace("\n", " | "))
            continue
        for loc in locs:
            by_airport.setdefault(loc, []).append(n)

    os.makedirs(args.output, exist_ok=True)
    for icao, notams in sorted(by_airport.items()):
        notams.sort(key=lambda n: -(n["from"] or 0))
        with open(os.path.join(args.output, f"{icao}.json"), "w", encoding="utf-8", newline="\n") as f:
            json.dump({"source": "FAA NOTAM Search (export PDF)", "queried": queried, "notams": notams}, f, ensure_ascii=False, indent=1)
            f.write("\n")
    total = sum(len(v) for v in by_airport.values())
    print(f"{total} NOTAM sur {len(by_airport)} aéroports -> {args.output} ({skipped} ignorés : annulations ou illisibles)")
    for icao, notams in sorted(by_airport.items(), key=lambda kv: -len(kv[1])):
        print(f"  {icao}: {len(notams)}")


if __name__ == "__main__":
    sys.exit(main())
